apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
spec:
  replicas: 2
  strategy: {}
  selector:
    matchLabels:
      app: insecure-app
      app: insecure-app
      app: insecure-app
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - containerPort: 90  
